openapi: 3.0.0
info:
  title: Generic Hyperledger Fabric API
  description: Contract agnostic REST API for experimenting with Fabric networks
  version: 0.1.0
tags:
  - name: blocks
    description: Block and awe
  - name: connection
    description: Connect! Connect!
  - name: jobs
    description: All work and no play
  - name: metadata
    description: About that
  - name: transactions
    description: Transaction-tastic
paths:
  /blocks:
    get:
      tags:
        - blocks
      summary: Returns a list of the most recent blocks
      responses:
        '200':
          description: Success
  /connection:
    get:
      tags:
        - connection
      summary: Returns the current connection profile
      responses:
        '200':
          description: Success
  /jobs:
    get:
      tags:
        - jobs
      summary: Returns a list of the most recent jobs
      responses:
        '200':
          description: Success
    post:
      tags:
        - jobs
      summary: Submits a new job
      responses:
        '202':
          description: Job submitted
  /metadata:
    get:
      tags:
        - metadata
      summary: Returns the smart contract metadata
      responses:
        '200':
          description: Success
  /transactions:
    get:
      tags:
        - transactions
      summary: Returns a list of the most recent transactions
      responses:
        '200':
          description: Success
